-- =====================================================================
-- Lakebase Support App — schema, permissions, and sample data
-- Run this in the Lakebase SQL Editor (databricks_postgres database).
--
-- BEFORE RUNNING: replace every <DATABRICKS_CLIENT_ID> below with your
-- app's service-principal client id (the DATABRICKS_CLIENT_ID from the
-- app's Environment tab). It looks like: 6b215d2b-f099-4bdb-900a-60837201ecec
-- =====================================================================

-- ---------------------------------------------------------------------
-- 0. OAuth auth for the app's service principal (run once per project)
-- ---------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS databricks_auth;

-- Create a Postgres role tied to the app's service principal.
-- Safe to skip/ignore an error if the role already exists.
SELECT databricks_create_role('<DATABRICKS_CLIENT_ID>', 'service_principal');

GRANT CONNECT ON DATABASE databricks_postgres TO "<DATABRICKS_CLIENT_ID>";
GRANT USAGE ON SCHEMA public TO "<DATABRICKS_CLIENT_ID>";

-- ---------------------------------------------------------------------
-- 1. Tables
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS ticket_messages;
DROP TABLE IF EXISTS tickets;

CREATE TABLE tickets (
    ticket_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       TEXT        NOT NULL,
    status      TEXT        NOT NULL DEFAULT 'open'
                            CHECK (status IN ('open', 'in_progress', 'resolved')),
    created_by  TEXT        NOT NULL,
    created_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- bonus columns (priority + category)
    priority    TEXT        NOT NULL DEFAULT 'medium'
                            CHECK (priority IN ('low', 'medium', 'high')),
    category    TEXT        NOT NULL DEFAULT 'general'
);

CREATE TABLE ticket_messages (
    message_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id     BIGINT    NOT NULL
                            REFERENCES tickets(ticket_id) ON DELETE CASCADE,
    message_text  TEXT      NOT NULL,
    author        TEXT      NOT NULL,
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_ticket_messages_ticket_id ON ticket_messages(ticket_id);

-- ---------------------------------------------------------------------
-- 2. Table permissions for the service principal
--    (service principals do NOT inherit default schema permissions)
-- ---------------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE tickets         TO "<DATABRICKS_CLIENT_ID>";
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE ticket_messages TO "<DATABRICKS_CLIENT_ID>";

-- ---------------------------------------------------------------------
-- 3. Sample data
--    3 tickets, >=2 messages each, 2+ distinct statuses
-- ---------------------------------------------------------------------
INSERT INTO tickets (title, status, created_by, priority, category) VALUES
    ('Cannot log into portal',        'open',        'alice@example.com', 'high',   'access'),
    ('Report export is missing rows',  'in_progress', 'bob@example.com',   'medium', 'reporting'),
    ('Request: add dark mode',         'resolved',    'carol@example.com', 'low',    'feature');

-- Messages reference tickets by title so this block is id-agnostic.
INSERT INTO ticket_messages (ticket_id, message_text, author)
SELECT ticket_id, m.message_text, m.author
FROM tickets t
JOIN (VALUES
    ('Cannot log into portal',       'I get "invalid credentials" even after a reset.', 'alice@example.com'),
    ('Cannot log into portal',       'Thanks for reporting — can you confirm your username?', 'support@example.com'),
    ('Report export is missing rows','The CSV export drops the last 200 rows.',          'bob@example.com'),
    ('Report export is missing rows','Reproduced it. Looks like a pagination bug.',       'support@example.com'),
    ('Report export is missing rows','Fix is in progress, ETA end of week.',              'support@example.com'),
    ('Request: add dark mode',       'Would love a dark theme for late-night work.',      'carol@example.com'),
    ('Request: add dark mode',       'Shipped in v2.3 — closing this out.',               'support@example.com')
) AS m(title, message_text, author)
  ON t.title = m.title;

-- ---------------------------------------------------------------------
-- 4. Quick verification
-- ---------------------------------------------------------------------
SELECT t.ticket_id, t.title, t.status, t.priority,
       COUNT(msg.message_id) AS message_count
FROM tickets t
LEFT JOIN ticket_messages msg ON msg.ticket_id = t.ticket_id
GROUP BY t.ticket_id, t.title, t.status, t.priority
ORDER BY t.ticket_id;
